import kitchenmusique.providers as providers

CONFIG_GPROXY_HOST = "192.168.1.83"
CONFIG_GPROXY_PORT = 9999

CONFIG_MPD_HOST = "192.168.1.83"
CONFIG_MPD_PORT = 6600

CONFIG_MPD_USE_PASSWORD = False
#CONFIG_MPD_PASSWORD = "hunter2"

CONFIG_ENABLED_PROVIDERS = [ providers.SputnikMusic ]